/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'dropkick' at '9/17/16 10:18 AM' with Gradle 2.14.1
 *
 * @author dropkick, @date 9/17/16 10:18 AM
 */
import java.io.IOException;
import java.util.Scanner;
import java.util.ArrayList;

import com.googlecode.lanterna.screen.Screen;
import com.googlecode.lanterna.screen.TerminalScreen;
import com.googlecode.lanterna.terminal.Terminal;
import com.googlecode.lanterna.terminal.DefaultTerminalFactory;
import com.googlecode.lanterna.graphics.TextGraphics;
import com.googlecode.lanterna.TerminalSize;
import com.googlecode.lanterna.TerminalPosition;
import com.googlecode.lanterna.TextColor;
import com.googlecode.lanterna.graphics.SimpleTheme;
import com.googlecode.lanterna.gui2.*;

public class Main {

    public static void main(String[] args) {
        try {
            Application app = new Application();
        } catch (IOException e) {
            e.printStackTrace();
        }

    }
}
