/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'dropkick' at '9/17/16 10:18 AM' with Gradle 2.14.1
 *
 * @author dropkick, @date 9/17/16 10:18 AM
 */
import java.io.IOException;
import java.util.Scanner;

public class Main {

    public static void main(String[] args) {
        Scanner s = new Scanner(System.in);
        
        System.out.println("sotrm: 0.0.0a");
        System.out.print("username: ");
        String username = s.nextLine();

        try {
            // Start server
            Server server = new Server(username);
            server.start();

            // Handle user input
            CommandParser parser = new CommandParser(server);
            String input = null;
            while (true) {
                if ((input = s.nextLine()) != null) {
                    parser.parseCommand(input);
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }

    }
}
