import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'dropkick' at '9/17/16 10:18 AM' with Gradle 2.14.1
 *
 * @author dropkick, @date 9/17/16 10:18 AM
 */
public class MainTest {
    /*
    @Test public void testSomeMainMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    */
}
